[theme]
base = "light"
backgroundColor = "#F7F1EB" # Warna cream cerah merata untuk menghilangkan kotak putih
secondaryBackgroundColor = "#EAE0D5"
textColor = "#3A2B24" # Teks bawaan jadi cokelat gelap
font = "sans serif"
